### ISSUE TITLE
Allow thread safe writing/recording

### ISSUE THREAD

**Issue by LeeCampbell** [HdrHistogram/HdrHistogram.NET#7]
Either create a thread safe implementation of each Histogram (16/32/64 bit) or provide a generic wrapper to allow synchronized access to them

 - [x] Thread safe writes
 - [x] Thread safe reads (via a recorder)

**Comment by giltene** [comment]
Experience in the Java world so far shows that with the combination ConcurrentHistogram and Recorder, synchronized versions don't have that much use. So I'd de-prioritize synchronized (or equivalents) in a port. I still support them in Java because they were there from the start...
ConcurrentHistogram supports safe multi-thread recording, but that still leaves you with "how do I safely read this thing" questions. A Recorder answers that with getIntervalHistogram() (wait free recording into an internal double-buffered ConcurrentHistogram, with potentially blocking readers).
Note that both Recorder and ConcurrentHistogram use WriterReaderPhaser for coordination. So that will also need porting. [In ConcurrentHistogram, the coordination is needed to support auto-sizing and shifting in a concurrent writer world...].

**Comment by LeeCampbell** [comment]
Check that we can close https://github.com/HdrHistogram/HdrHistogram/issues/58 in the same feature.

**Comment by LeeCampbell** [comment]
Closed by #30 and #32
